---
# Default is to log in as root
#ansible_user: root
#remote_user: root

ctfusers_pw_salt: "3vJ6Hxn6"
ctfusers_login_prefix: "snoopy"

ctflevels:
    - level: 0
      networks: 1
      password: "snoopy0"
      login_message: |4

            Welcome!

            Remember to review the "tcpdump" man page. Syntax for filter expressions
            can be found in the "pcap-filter" man page, it'll come handy soon.

            The objective is to find a password for the next level (snoopy1). You
            need to capture the password from the network traffic. Often there will
            be a lot of different traffic on the wire and only correct subset of
            the traffic need to captured. The level's story describes what kind of
            traffic needs to captured to unlock the password for the next level.

            Backstory for this game is this. You're a hacker, and, as a hacker,
            you've always been curious. Tools that unveil and analyze network
            traffic carry enormous power... Power to raise curiosity, of course.
            Let's see what secrets lie ahead. Shall we?

            Now, run tcpdump (without sudo) and see what happens.
    - level: 1
      networks: 1
      password: "snoopy1"
      login_message: |4

            From: Security@acme.corp
            To: undisclosed-recipients;
            Subject: Protocols upgrade

            Company-wide notice:

            We're upgrading protocols so that password were not revealed by simply
            running a tcpdump command. For compatibility, passwords are passed as
            before as packet contents.

            Regards
    - level: 2
      networks: 2
      password: "snoopy2"
      login_message: |4

            From: Alistair.Silva@acme.corp
            To: Maya.Montes@acme.corp
            Subject: Re: Server installation

            Hi Maya, as requested by Mr. Knox, I hooked up your new server to two
            networks that you're requested. Our usual control path network is
            connected to the second port, is that correct?

            Curious what's another secret project you're working on again so you
            need so much traffic...

            Alistair
    - level: 3
      networks: 2
      password: "snoopy3"
      login_message: |4

            From: IT@acme.corp
            To: undisclosed-recipients;
            Subject: Planned Router upgrade

            Hi, please note, we plan to install new router this Saturday as a first
            step of our infrastructure upgrade. Please let us know if you'll
            encounter something unexpected on Monday, like connection issues,
            or, especially, unexpected traffic on a control network.

            Also note, authentication server address will not be changed this time,
            so you can safely connect to the same IP address if you need to authenticate.

            Jack

    - level: 4
      networks: 2
      password: "snoopy4"
      login_message: |4

            You win!
    - level: 5
      networks: 2
      password: "snoopy5"
      login_message: ""
    - level: 6
      networks: 0
      password: "snoopy6"
      last: true
      login_message: ""

ctfpackage_name: "traffic_servers"
ctfpackage_version: "1.0.0"

...
